version: "3.7"
services:

  db:
    image: postgres
    restart: always
    
    environment:
      - POSTGRES_DB=tutor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

    ports:
      - 5432:5432


  tutorweb:
    build: .
    restart: always

    volumes:
      - .:/app
      - .:/uploads

    ports:
      - "5000:5000"

     
    depends_on:
      - db



  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
   