version: "3.7"
services:
 
    build: .
    restart: always

    volumes:
      - .:/app
      - .:/uploads

    ports:
      - "9000:9000"


  redis:
    restart: always
    image: redis:latest
    ports:
      - "9000:9000"
   